apiVersion: v1
kind: Service
metadata:
  name: controller-svc
spec:
  selector:
    app: ngi
  
  ports:

    - name: tcp
      protocol: TCP
      port: 7443
      targetPort: 8443
    - name: tcp2
      protocol: TCP
      port: 7444
      targetPort: 8444
    - name: tcp3
      protocol: TCP
      port: 9443
      targetPort: 9443
