# fluentd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: shamyy/magma:flunted
          ports:
            - containerPort: 24224
              protocol: TCP
            - containerPort: 24224
              protocol: UDP
            - containerPort: 24225
              protocol: TCP
            - containerPort: 24225
              protocol: UDP
          volumeMounts:
            - name: fluentd-config
              mountPath: /app/magma/flunted-conf
            - name: magma-certs
              mountPath: /app/magma/certs
      
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: magma-certs
          hostPath:
            path: /var/opt/magma/certs
       
          