apiVersion: v1
kind: Service
metadata:
  name: controller-service
spec:
  selector:
    app: nginx 
  ports:
    - name: tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: tcp2
      protocol: TCP
      port: 8444
      targetPort: 8444
    - name: tcp3
      protocol: TCP
      port: 9443
      targetPort: 9443
