apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager
          ports:
            - containerPort: 9093
              protocol: TCP
          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /etc/alertmanager
              readOnly: true
      restartPolicy: Always


      volumes:
        - name: alertmanager-config-volume
          configMap:
            name: alertmanager-config-volume
