apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-grafana
  template:
    metadata:
      labels:
        app: user-grafana
    spec:
      containers:
        - name: user-grafana
          image: grafana/grafana:6.6.2
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_USERS_AUTO_ASSIGN_ORG
              value: "false"
            - name: GF_AUTH_PROXY_ENABLED
              value: "true"
            - name: GF_AUTH_PROXY_HEADER_NAME
              value: X-WEBAUTH-USER
            - name: GF_AUTH_PROXY_HEADER_PROPERTY
              value: username
            - name: GF_AUTH_PROXY_AUTO_SIGN_UP
              value: "false"
            - name: GF_SERVER_ROOT_URL
              value: /grafana
          volumeMounts:
            - name: user-grafana-data
              mountPath: /var/lib/grafana


      restartPolicy: Always  

      volumes:
        - name: user-grafana-data
          persistentVolumeClaim:
            claimName: user-grafana-pvc
