apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
        - name: thanos-store
          image: thanosio/thanos:master-2020-09-30-e4941a5c
        
          args:
            - "store"
            - "--objstore.config-file=/etc/thanos/objstore.yml"
          volumeMounts:
            - name: thanos-config
              mountPath: /etc/thanos
              readOnly: true
      volumes:
        - name: thanos-config
          configMap:
            name: thanos-configmap
